close all;clear;clc;
data = csvread('heatmap_data.csv');
imagesc(data);
set(gca, 'YDir', 'normal');
axis equal;
axis tight;
colormap(hot);
colorbar;
xlabel('Cột lưới');
ylabel('Hàng lưới');
title('Biểu đồ trùng lặp quỹ đạo');
